FROM node:22-bookworm-slim AS build

WORKDIR /app/mesonero-web

COPY package.json /app/package.json
COPY app/mesonero-web/package*.json ./

RUN npm install

COPY app/mesonero-web ./

RUN npm run build

FROM nginx:1.27-alpine

COPY app/mesonero-web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/mesonero-web/dist /usr/share/nginx/html

EXPOSE 80
