FROM node:22-bookworm-slim

WORKDIR /app/backend

COPY package.json /app/package.json
COPY services/backend/package*.json ./

RUN npm install --omit=dev

COPY services/backend ./

EXPOSE 5000

CMD ["npm", "start"]
