FROM node:22-bookworm-slim AS build

WORKDIR /app/caja-web

COPY app/caja/web/package*.json ./

RUN npm install

COPY app/caja/web ./

RUN npm run build

FROM nginx:1.27-alpine

COPY app/caja/web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/caja-web/dist /usr/share/nginx/html

EXPOSE 80
